version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    environment:
      COVERALLS_REPO_TOKEN: VDOU1pSRZY3641ry3AAekApDkiXJDAnLg
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --save-dev coveralls
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Upload coverage report to Coveralls
          command: cat ./coverage/lcov.info | coveralls

