name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Run tests and coverage
      run: npm test -- --coverage
    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2.1.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}


