version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
  jobs:
    build:
      docker:
        - image: circleci/node:10.0.0
          steps:
            - checkout
            - run:
              name: Install dependencies and Make
              command: npm install && make test-coverage
            - run:
              name: Run tests
              command: npm test
            - coveralls/upload
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
