version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run test:ci
  deploy:
    docker:
      - image: alpine
    steps:
      - run: apk add --update git
      - run: npm install -g coveralls
      - run: coveralls < coverage/lcov.info
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
